version: '3'
services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: ms-postgres
    environment:
      POSTGRES_DB: ms_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
